"""
Authentication router for user registration, login, logout, and CSRF
"""
import os
from fastapi import APIRouter, HTTPException, Depends, Response, Request

from models.core import User, UserCreate, UserLogin
from services.auth_service import AuthService
from dependencies import get_auth_service, get_database


# Router instance
router = APIRouter(prefix="/auth", tags=["authentication"])


@router.post("/register")
async def register_user(
    user_data: UserCreate, 
    response: Response,
    auth_service: AuthService = Depends(get_auth_service),
    db = Depends(get_database)
):
    """Register a new user with secure httpOnly cookie authentication"""
    
    # Check if user already exists
    existing_user = await db.users.find_one({"email": user_data.email})
    if existing_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # Hash password and create user
    password_hash = auth_service.hash_password(user_data.password)
    user = User(
        **user_data.dict(exclude={'password'}),
        password_hash=password_hash
    )
    
    # Save to database
    await db.users.insert_one(user.dict())
    
    # Create JWT token
    token = auth_service.create_jwt_token(user.user_id, user.email)
    
    # Set secure httpOnly cookie
    auth_service.set_secure_cookie(response, token)
    
    return {
        "message": "User registered successfully",
        "token": token,  # For backward compatibility with Bearer token auth
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "exam_type": user.exam_type
        }
    }


@router.post("/login")
async def login_user(
    login_data: UserLogin, 
    response: Response,
    auth_service: AuthService = Depends(get_auth_service),
    db = Depends(get_database)
):
    """Login user with secure httpOnly cookie authentication"""
    
    # Find user
    user_doc = await db.users.find_one({"email": login_data.email})
    if not user_doc:
        raise HTTPException(status_code=401, detail="Invalid email or password")
    
    user = User(**user_doc)
    
    # Verify password
    if not auth_service.verify_password(login_data.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid email or password")
    
    # Create JWT token
    token = auth_service.create_jwt_token(user.user_id, user.email)
    
    # Set secure httpOnly cookie
    auth_service.set_secure_cookie(response, token)
    
    return {
        "message": "Login successful",
        "token": token,  # For backward compatibility with Bearer token auth
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "exam_type": user.exam_type,
            "subscription_type": user.subscription_type
        }
    }


@router.post("/logout")
async def logout_user(
    response: Response,
    auth_service: AuthService = Depends(get_auth_service)
):
    """Logout user by clearing the authentication cookie"""
    auth_service.clear_secure_cookie(response)
    return {"message": "Logout successful"}


@router.get("/csrf-token")
async def get_csrf_token(request: Request):
    """Get CSRF token for secure form submissions"""
    # The CSRF token is automatically generated by the middleware
    # and available in the request context
    csrf_token = request.scope.get('csrf_token', '')
    return {"csrf_token": csrf_token}


@router.post("/google/callback")
async def google_auth_callback(
    auth_data: 'GoogleAuthCallback',
    response: Response,
    db = Depends(get_database)
):
    """
    Handle Google OAuth callback from Emergent Social Login
    Exchange session_id for user data and create/update user
    """
    from models.core import GoogleAuthCallback, User
    from datetime import datetime, timezone, timedelta
    
    # Check if user exists by Google ID or email
    existing_user = await db.users.find_one({
        "$or": [
            {"google_id": auth_data.id},
            {"email": auth_data.email}
        ]
    })
    
    if existing_user:
        # Update session token and expiry
        session_expiry = datetime.now(timezone.utc) + timedelta(days=7)
        await db.users.update_one(
            {"user_id": existing_user["user_id"]},
            {"$set": {
                "session_token": auth_data.session_token,
                "session_expiry": session_expiry,
                "google_id": auth_data.id,  # Ensure google_id is set
                "photo_url": auth_data.picture,  # Update photo
                "auth_provider": "google"
            }}
        )
        user = User(**existing_user)
        user.session_token = auth_data.session_token
        user.session_expiry = session_expiry
        user.google_id = auth_data.id
        user.photo_url = auth_data.picture
    else:
        # Create new user
        session_expiry = datetime.now(timezone.utc) + timedelta(days=7)
        user = User(
            full_name=auth_data.name,
            email=auth_data.email,
            google_id=auth_data.id,
            photo_url=auth_data.picture,
            auth_provider="google",
            session_token=auth_data.session_token,
            session_expiry=session_expiry,
            profile_completed=False  # Needs profile setup
        )
        await db.users.insert_one(user.dict())
    
    # Set httpOnly cookie with session token
    is_production = os.environ.get('ENVIRONMENT', 'development') == 'production'
    response.set_cookie(
        key="dhruv_ai_session",
        value=auth_data.session_token,
        max_age=7 * 24 * 60 * 60,  # 7 days
        httponly=True,
        secure=is_production,
        samesite="lax",
        path="/"
    )
    
    return {
        "message": "Authentication successful",
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "photo_url": user.photo_url,
            "exam_type": user.exam_type,
            "profile_completed": user.profile_completed,
            "subscription_type": user.subscription_type
        }
    }


@router.get("/session")
async def get_session(
    request: Request,
    db = Depends(get_database)
):
    """
    Check existing session from cookie or Authorization header
    Returns current user if session is valid
    """
    from models.core import User
    from datetime import datetime, timezone
    
    # Try cookie first
    session_token = request.cookies.get("dhruv_ai_session")
    
    # Fallback to Authorization header
    if not session_token:
        auth_header = request.headers.get("Authorization")
        if auth_header and auth_header.startswith("Bearer "):
            session_token = auth_header.split(" ")[1]
    
    # Also check old JWT cookie for backward compatibility
    if not session_token:
        session_token = request.cookies.get("dhruv_ai_auth")
    
    if not session_token:
        raise HTTPException(status_code=401, detail="No active session")
    
    # Find user with valid session
    user_doc = await db.users.find_one({
        "$or": [
            {
                "session_token": session_token,
                "session_expiry": {"$gt": datetime.now(timezone.utc)}
            },
            # Legacy JWT token support (for old users)
            {"user_id": {"$exists": True}}  # Verify JWT separately below
        ]
    })
    
    if not user_doc:
        raise HTTPException(status_code=401, detail="Session expired or invalid")
    
    user = User(**user_doc)
    
    # Check if session expired (for new OAuth users)
    if user.session_expiry and user.session_expiry < datetime.now(timezone.utc):
        raise HTTPException(status_code=401, detail="Session expired")
    
    return {
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "photo_url": user.photo_url,
            "exam_type": user.exam_type,
            "profile_completed": user.profile_completed,
            "subscription_type": user.subscription_type
        }
    }


@router.post("/profile/complete")
async def complete_profile(
    profile_data: 'ProfileCompleteRequest',
    request: Request,
    db = Depends(get_database)
):
    """
    Complete user profile after first Gmail login
    Sets profile_completed to True
    """
    from models.core import ProfileCompleteRequest, User
    from datetime import datetime, timezone
    
    # Get current user from session
    session_token = request.cookies.get("dhruv_ai_session")
    if not session_token:
        auth_header = request.headers.get("Authorization")
        if auth_header and auth_header.startswith("Bearer "):
            session_token = auth_header.split(" ")[1]
    
    if not session_token:
        raise HTTPException(status_code=401, detail="Authentication required")
    
    user_doc = await db.users.find_one({
        "session_token": session_token,
        "session_expiry": {"$gt": datetime.now(timezone.utc)}
    })
    
    if not user_doc:
        raise HTTPException(status_code=401, detail="Session expired")
    
    # Update user profile
    update_data = {
        "exam_type": profile_data.exam_type,
        "profile_completed": True
    }
    
    if profile_data.study_goal:
        update_data["study_goal"] = profile_data.study_goal
    if profile_data.preferred_mode:
        update_data["preferred_mode"] = profile_data.preferred_mode
    if profile_data.timezone:
        update_data["timezone"] = profile_data.timezone
    if profile_data.country:
        update_data["country"] = profile_data.country
    if profile_data.target_year:
        update_data["target_year"] = profile_data.target_year
    
    await db.users.update_one(
        {"user_id": user_doc["user_id"]},
        {"$set": update_data}
    )
    
    # Fetch updated user
    updated_user_doc = await db.users.find_one({"user_id": user_doc["user_id"]})
    user = User(**updated_user_doc)
    
    return {
        "message": "Profile completed successfully",
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "photo_url": user.photo_url,
            "exam_type": user.exam_type,
            "profile_completed": user.profile_completed,
            "subscription_type": user.subscription_type
        }
    }