"""
Authentication router for user registration, login, logout, and CSRF
"""
from fastapi import APIRouter, HTTPException, Depends, Response, Request
from motor.motor_asyncio import AsyncIOMotorClient

from ..models.core import User, UserCreate, UserLogin
from ..services.auth_service import AuthService


# Router instance
router = APIRouter(prefix="/auth", tags=["authentication"])


# Dependency to get auth service
def get_auth_service(db: AsyncIOMotorClient, jwt_secret: str) -> AuthService:
    """Dependency to create auth service instance"""
    return AuthService(db, jwt_secret)


@router.post("/register")
async def register_user(
    user_data: UserCreate, 
    response: Response,
    auth_service: AuthService = Depends(get_auth_service)
):
    """Register a new user with secure httpOnly cookie authentication"""
    
    # Check if user already exists
    existing_user = await auth_service.db.users.find_one({"email": user_data.email})
    if existing_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # Hash password and create user
    password_hash = auth_service.hash_password(user_data.password)
    user = User(
        **user_data.dict(exclude={'password'}),
        password_hash=password_hash
    )
    
    # Save to database
    await auth_service.db.users.insert_one(user.dict())
    
    # Create JWT token
    token = auth_service.create_jwt_token(user.user_id, user.email)
    
    # Set secure httpOnly cookie
    auth_service.set_secure_cookie(response, token)
    
    return {
        "message": "User registered successfully",
        "token": token,  # For backward compatibility with Bearer token auth
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "exam_type": user.exam_type
        }
    }


@router.post("/login")
async def login_user(
    login_data: UserLogin, 
    response: Response,
    auth_service: AuthService = Depends(get_auth_service)
):
    """Login user with secure httpOnly cookie authentication"""
    
    # Find user
    user_doc = await auth_service.db.users.find_one({"email": login_data.email})
    if not user_doc:
        raise HTTPException(status_code=401, detail="Invalid email or password")
    
    user = User(**user_doc)
    
    # Verify password
    if not auth_service.verify_password(login_data.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid email or password")
    
    # Create JWT token
    token = auth_service.create_jwt_token(user.user_id, user.email)
    
    # Set secure httpOnly cookie
    auth_service.set_secure_cookie(response, token)
    
    return {
        "message": "Login successful",
        "token": token,  # For backward compatibility with Bearer token auth
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "exam_type": user.exam_type,
            "subscription_type": user.subscription_type
        }
    }


@router.post("/logout")
async def logout_user(
    response: Response,
    auth_service: AuthService = Depends(get_auth_service)
):
    """Logout user by clearing the authentication cookie"""
    auth_service.clear_secure_cookie(response)
    return {"message": "Logout successful"}


@router.get("/csrf-token")
async def get_csrf_token(request: Request):
    """Get CSRF token for secure form submissions"""
    # The CSRF token is automatically generated by the middleware
    # and available in the request context
    csrf_token = request.scope.get('csrf_token', '')
    return {"csrf_token": csrf_token}