"""
Authentication router for user registration, login, logout, and CSRF
"""
import os
from fastapi import APIRouter, HTTPException, Depends, Response, Request
from fastapi.responses import RedirectResponse
from urllib.parse import urlencode

from models.core import User, UserCreate, UserLogin, ProfileCompleteRequest, GoogleAuthCallback
from services.auth_service import AuthService
from services.oauth_state_store import OAuthStateStore
from dependencies import get_auth_service, get_database


# Router instance
router = APIRouter(prefix="/auth", tags=["authentication"])


@router.post("/register")
async def register_user(
    user_data: UserCreate, 
    response: Response,
    auth_service: AuthService = Depends(get_auth_service),
    db = Depends(get_database)
):
    """Register a new user with secure httpOnly cookie authentication"""
    
    # Check if user already exists
    existing_user = await db.users.find_one({"email": user_data.email})
    if existing_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # Hash password and create user
    password_hash = auth_service.hash_password(user_data.password)
    user = User(
        **user_data.dict(exclude={'password'}),
        password_hash=password_hash
    )
    
    # Save to database
    await db.users.insert_one(user.dict())
    
    # Create JWT token
    token = auth_service.create_jwt_token(user.user_id, user.email)
    
    # Set secure httpOnly cookie
    auth_service.set_secure_cookie(response, token)
    
    return {
        "message": "User registered successfully",
        "token": token,  # For backward compatibility with Bearer token auth
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "exam_type": user.exam_type
        }
    }


@router.post("/login")
async def login_user(
    login_data: UserLogin, 
    response: Response,
    auth_service: AuthService = Depends(get_auth_service),
    db = Depends(get_database)
):
    """Login user with secure httpOnly cookie authentication"""
    
    # Find user
    user_doc = await db.users.find_one({"email": login_data.email})
    if not user_doc:
        raise HTTPException(status_code=401, detail="Invalid email or password")
    
    user = User(**user_doc)
    
    # Verify password
    if not auth_service.verify_password(login_data.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid email or password")
    
    # Create JWT token
    token = auth_service.create_jwt_token(user.user_id, user.email)
    
    # Set secure httpOnly cookie
    auth_service.set_secure_cookie(response, token)
    
    return {
        "message": "Login successful",
        "token": token,  # For backward compatibility with Bearer token auth
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "exam_type": user.exam_type,
            "subscription_type": user.subscription_type,
            "profile_completed": user.profile_completed
        }
    }


@router.post("/logout")
async def logout_user(
    response: Response,
    request: Request,
    auth_service: AuthService = Depends(get_auth_service),
    db = Depends(get_database)
):
    """Logout user by clearing the authentication cookie and session"""
    
    # Get session token
    session_token = request.cookies.get("dhruv_ai_session") or request.cookies.get("dhruv_ai_auth")
    
    # Clear session from database if exists
    if session_token:
        await db.users.update_many(
            {"session_token": session_token},
            {"$set": {
                "session_token": None,
                "session_expiry": None
            }}
        )
    
    # Clear cookies
    auth_service.clear_secure_cookie(response)
    backend_url = os.getenv('BACKEND_URL', 'http://localhost:8001')
    is_https = backend_url.startswith('https://')
    response.delete_cookie(
        key="dhruv_ai_session",
        httponly=True,
        secure=is_https,
        samesite="none",
        path="/"
    )
    
    return {"message": "Logout successful"}


@router.get("/csrf-token")
async def get_csrf_token(request: Request):
    """Get CSRF token for secure form submissions"""
    # The CSRF token is automatically generated by the middleware
    # and available in the request context
    csrf_token = request.scope.get('csrf_token', '')
    return {"csrf_token": csrf_token}


@router.get("/google/login")
async def google_login(request: Request, db = Depends(get_database)):
    """
    Initiate Google OAuth flow
    Redirects user to Google sign-in
    """
    try:
        # Get the base URL from environment - MUST be production domain
        backend_url = os.getenv('BACKEND_URL')
        if not backend_url:
            raise ValueError("BACKEND_URL environment variable is required for OAuth")
        redirect_uri = f"{backend_url}/api/auth/google/callback"
        
        print(f"🔐 Initiating Google OAuth...")
        print(f"📍 Redirect URI: {redirect_uri}")
        print(f"🔑 Client ID: {os.getenv('GOOGLE_CLIENT_ID', 'NOT_SET')[:20]}...")
        
        # Create and store state in database
        state_store = OAuthStateStore(db)
        state = await state_store.create_state()
        print(f"🎫 Created OAuth state: {state[:20]}...")
        
        # Build Google OAuth URL manually with our state
        auth_url = "https://accounts.google.com/o/oauth2/v2/auth"
        params = {
            "client_id": os.getenv('GOOGLE_CLIENT_ID'),
            "redirect_uri": redirect_uri,
            "response_type": "code",
            "scope": "openid email profile",
            "state": state,
            "prompt": "select_account"
        }
        
        google_oauth_url = f"{auth_url}?{urlencode(params)}"
        print(f"🔄 Redirecting to Google...")
        
        return RedirectResponse(url=google_oauth_url)
    except Exception as e:
        print(f"❌ Error in google_login: {str(e)}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"OAuth initialization failed: {str(e)}")


@router.get("/google/callback")
async def google_callback(
    request: Request,
    response: Response,
    db = Depends(get_database)
):
    """
    Google OAuth callback handler
    Receives authorization code and exchanges for user info
    """
    from models.core import User
    from datetime import datetime, timezone, timedelta
    import secrets
    import traceback
    import httpx
    
    try:
        print("🔐 Starting Google OAuth callback processing...")
        
        # Get state and code from query params
        state = request.query_params.get('state')
        code = request.query_params.get('code')
        error = request.query_params.get('error')
        
        print(f"📥 Query params - state: {state[:20] if state else 'None'}..., code: {code[:20] if code else 'None'}..., error: {error}")
        
        if error:
            print(f"❌ OAuth error from Google: {error}")
            frontend_url = os.getenv('FRONTEND_URL')
            if not frontend_url:
                frontend_url = os.getenv('BACKEND_URL', 'http://localhost:3000')
            return RedirectResponse(url=f"{frontend_url}/login?error={error}")
        
        if not state or not code:
            print("❌ Missing state or code parameter")
            raise HTTPException(status_code=400, detail="Missing state or code parameter")
        
        # Verify state
        state_store = OAuthStateStore(db)
        is_valid = await state_store.verify_state(state)
        
        if not is_valid:
            print(f"❌ Invalid or expired OAuth state: {state[:20]}...")
            raise HTTPException(status_code=400, detail="Invalid or expired OAuth state")
        
        print("✅ OAuth state verified")
        
        # Exchange authorization code for tokens
        token_url = "https://oauth2.googleapis.com/token"
        backend_url = os.getenv('BACKEND_URL')
        if not backend_url:
            raise ValueError("BACKEND_URL environment variable is required for OAuth")
        redirect_uri = f"{backend_url}/api/auth/google/callback"
        
        token_data = {
            "code": code,
            "client_id": os.getenv('GOOGLE_CLIENT_ID'),
            "client_secret": os.getenv('GOOGLE_CLIENT_SECRET'),
            "redirect_uri": redirect_uri,
            "grant_type": "authorization_code"
        }
        
        print("📡 Exchanging authorization code for access token...")
        async with httpx.AsyncClient() as client:
            token_response = await client.post(token_url, data=token_data)
            
            if token_response.status_code != 200:
                print(f"❌ Token exchange failed: {token_response.text}")
                raise HTTPException(status_code=400, detail="Failed to exchange authorization code")
            
            tokens = token_response.json()
            access_token = tokens.get('access_token')
            id_token = tokens.get('id_token')
            
            print(f"✅ Tokens received")
            
            # Get user info from Google
            userinfo_url = "https://www.googleapis.com/oauth2/v2/userinfo"
            userinfo_response = await client.get(
                userinfo_url,
                headers={"Authorization": f"Bearer {access_token}"}
            )
            
            if userinfo_response.status_code != 200:
                print(f"❌ Failed to get user info: {userinfo_response.text}")
                raise HTTPException(status_code=400, detail="Failed to get user info from Google")
            
            user_info = userinfo_response.json()
        
        google_id = user_info['id']
        email = user_info['email']
        name = user_info.get('name', email.split('@')[0])
        picture = user_info.get('picture', '')
        
        print(f"👤 User info - Email: {email}, Name: {name}, Google ID: {google_id[:10]}...")
        
        # Check if user exists
        print("🔍 Checking if user exists in database...")
        existing_user = await db.users.find_one({
            "$or": [
                {"google_id": google_id},
                {"email": email}
            ]
        })
        
        # Generate session token
        session_token = secrets.token_urlsafe(32)
        session_expiry = datetime.now(timezone.utc) + timedelta(days=7)
        
        if existing_user:
            print(f"✅ Existing user found: {existing_user.get('user_id')}")
            # Update existing user
            await db.users.update_one(
                {"user_id": existing_user["user_id"]},
                {"$set": {
                    "session_token": session_token,
                    "session_expiry": session_expiry.isoformat(),
                    "google_id": google_id,
                    "photo_url": picture,
                    "auth_provider": "google"
                }}
            )
            profile_completed = existing_user.get('profile_completed', False)
            print(f"📝 Profile completed status: {profile_completed}")
        else:
            print("➕ Creating new user...")
            # Create new user
            user = User(
                full_name=name,
                email=email,
                google_id=google_id,
                photo_url=picture,
                auth_provider="google",
                session_token=session_token,
                session_expiry=session_expiry,
                profile_completed=False
            )
            user_dict = user.dict()
            # Convert datetime to ISO string for MongoDB
            if isinstance(user_dict.get('session_expiry'), datetime):
                user_dict['session_expiry'] = user_dict['session_expiry'].isoformat()
            
            await db.users.insert_one(user_dict)
            profile_completed = False
            print(f"✅ New user created: {user.user_id}")
        
        # MODERN OAUTH APPROACH: Return session token via URL parameter
        # This is more reliable than cookies in redirect responses
        # Frontend will capture the token and set it properly
        
        # Redirect to frontend based on profile completion
        frontend_url = os.getenv('FRONTEND_URL') or os.getenv('BACKEND_URL', 'http://localhost:3000')
        
        # For new users, pass user info in URL for ProfileSetup display
        if not profile_completed:
            from urllib.parse import quote
            redirect_url = (
                f"{frontend_url}/profile-setup?"
                f"session_token={session_token}&"
                f"name={quote(name)}&"
                f"email={quote(email)}&"
                f"photo_url={quote(picture)}"
            )
        else:
            redirect_url = f"{frontend_url}/dashboard?session_token={session_token}"
        
        print(f"🔄 Redirecting to: {redirect_url}")
        return RedirectResponse(url=redirect_url)
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Google OAuth error: {str(e)}")
        print(f"❌ Error type: {type(e).__name__}")
        print(f"❌ Full traceback:")
        traceback.print_exc()
        
        # Redirect to login with error
        frontend_url = os.getenv('FRONTEND_URL') or os.getenv('BACKEND_URL', 'http://localhost:3000')
        return RedirectResponse(url=f"{frontend_url}/login?error=oauth_failed")


@router.post("/google/session")
async def exchange_google_session(
    request: Request,
    response: Response,
    db = Depends(get_database)
):
    """
    Exchange Emergent session_id for user data
    Acts as a proxy to avoid CORS issues
    """
    import aiohttp
    
    try:
        body = await request.json()
        session_id = body.get('session_id')
        
        if not session_id:
            raise HTTPException(status_code=400, detail="session_id is required")
        
        # Call Emergent API - use environment variable for flexibility
        emergent_auth_api_url = os.getenv(
            'EMERGENT_AUTH_API_URL',
            'https://demobackend.emergentagent.com/auth/v1/env/oauth/session-data'
        )
        
        async with aiohttp.ClientSession() as session:
            async with session.get(
                emergent_auth_api_url,
                headers={'X-Session-ID': session_id}
            ) as resp:
                if resp.status != 200:
                    error_text = await resp.text()
                    raise HTTPException(
                        status_code=resp.status,
                        detail=f"Emergent API error: {error_text}"
                    )
                
                session_data = await resp.json()
                
                # Now process the login
                result = await process_google_login(session_data, db)
                
                # Set httpOnly cookie with session token
                backend_url = os.getenv('BACKEND_URL', 'http://localhost:8001')
                is_https = backend_url.startswith('https://')
                # Extract domain dynamically from BACKEND_URL
                cookie_domain = None
                if is_https and backend_url:
                    from urllib.parse import urlparse
                    parsed = urlparse(backend_url)
                    hostname = parsed.hostname
                    if hostname and '.' in hostname:
                        # Extract root domain (e.g., emergent.host from seamless-auth-1.emergent.host)
                        parts = hostname.split('.')
                        if len(parts) >= 2:
                            cookie_domain = f".{'.'.join(parts[-2:])}"
                
                response.set_cookie(
                    key="dhruv_ai_session",
                    value=session_data['session_token'],
                    max_age=7 * 24 * 60 * 60,  # 7 days
                    httponly=True,
                    secure=is_https,
                    samesite="none",
                    path="/",
                    domain=cookie_domain
                )
                
                return result
                
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Session exchange failed: {str(e)}"
        )


async def process_google_login(session_data: dict, db):
    """Helper function to process Google login"""
    from models.core import User
    from datetime import datetime, timezone, timedelta
    
    # Check if user exists by Google ID or email
    existing_user = await db.users.find_one({
        "$or": [
            {"google_id": session_data['id']},
            {"email": session_data['email']}
        ]
    })
    
    if existing_user:
        # Update session token and expiry
        session_expiry = datetime.now(timezone.utc) + timedelta(days=7)
        await db.users.update_one(
            {"user_id": existing_user["user_id"]},
            {"$set": {
                "session_token": session_data['session_token'],
                "session_expiry": session_expiry.isoformat(),
                "google_id": session_data['id'],
                "photo_url": session_data['picture'],
                "auth_provider": "google"
            }}
        )
        user = User(**existing_user)
        user.session_token = session_data['session_token']
        user.session_expiry = session_expiry
        user.google_id = session_data['id']
        user.photo_url = session_data['picture']
    else:
        # Create new user
        session_expiry = datetime.now(timezone.utc) + timedelta(days=7)
        user = User(
            full_name=session_data['name'],
            email=session_data['email'],
            google_id=session_data['id'],
            photo_url=session_data['picture'],
            auth_provider="google",
            session_token=session_data['session_token'],
            session_expiry=session_expiry,
            profile_completed=False
        )
        user_dict = user.dict()
        # Convert datetime to ISO string for MongoDB
        if isinstance(user_dict.get('session_expiry'), datetime):
            user_dict['session_expiry'] = user_dict['session_expiry'].isoformat()
        await db.users.insert_one(user_dict)
    
    return {
        "message": "Authentication successful",
        "session_token": session_data['session_token'],
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "photo_url": user.photo_url,
            "exam_type": user.exam_type,
            "profile_completed": user.profile_completed,
            "subscription_type": user.subscription_type
        }
    }


@router.post("/google/callback")
async def google_auth_callback(
    auth_data: GoogleAuthCallback,
    response: Response,
    db = Depends(get_database)
):
    """
    Handle Google OAuth callback from Emergent Social Login
    Exchange session_id for user data and create/update user
    """
    from models.core import User
    from datetime import datetime, timezone, timedelta
    
    # Check if user exists by Google ID or email
    existing_user = await db.users.find_one({
        "$or": [
            {"google_id": auth_data.id},
            {"email": auth_data.email}
        ]
    })
    
    if existing_user:
        # Update session token and expiry
        session_expiry = datetime.now(timezone.utc) + timedelta(days=7)
        await db.users.update_one(
            {"user_id": existing_user["user_id"]},
            {"$set": {
                "session_token": auth_data.session_token,
                "session_expiry": session_expiry.isoformat(),
                "google_id": auth_data.id,  # Ensure google_id is set
                "photo_url": auth_data.picture,  # Update photo
                "auth_provider": "google"
            }}
        )
        user = User(**existing_user)
        user.session_token = auth_data.session_token
        user.session_expiry = session_expiry
        user.google_id = auth_data.id
        user.photo_url = auth_data.picture
    else:
        # Create new user
        session_expiry = datetime.now(timezone.utc) + timedelta(days=7)
        user = User(
            full_name=auth_data.name,
            email=auth_data.email,
            google_id=auth_data.id,
            photo_url=auth_data.picture,
            auth_provider="google",
            session_token=auth_data.session_token,
            session_expiry=session_expiry,
            profile_completed=False  # Needs profile setup
        )
        user_dict = user.dict()
        # Convert datetime to ISO string for MongoDB
        if isinstance(user_dict.get('session_expiry'), datetime):
            user_dict['session_expiry'] = user_dict['session_expiry'].isoformat()
        await db.users.insert_one(user_dict)
    
    # Set httpOnly cookie with session token
    backend_url = os.getenv('BACKEND_URL', 'http://localhost:8001')
    is_https = backend_url.startswith('https://')
    
    # Extract domain dynamically from BACKEND_URL
    cookie_domain = None
    if is_https and backend_url:
        from urllib.parse import urlparse
        parsed = urlparse(backend_url)
        hostname = parsed.hostname
        if hostname and '.' in hostname:
            # Extract root domain (e.g., emergent.host from seamless-auth-1.emergent.host)
            parts = hostname.split('.')
            if len(parts) >= 2:
                cookie_domain = f".{'.'.join(parts[-2:])}"
    
    response.set_cookie(
        key="dhruv_ai_session",
        value=auth_data.session_token,
        max_age=7 * 24 * 60 * 60,  # 7 days
        httponly=True,
        secure=is_https,
        samesite="none",
        path="/",
        domain=cookie_domain
    )
    
    return {
        "message": "Authentication successful",
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "photo_url": user.photo_url,
            "exam_type": user.exam_type,
            "profile_completed": user.profile_completed,
            "subscription_type": user.subscription_type
        }
    }


@router.get("/session")
async def get_session(
    request: Request,
    db = Depends(get_database)
):
    """
    Check existing session from cookie or Authorization header
    Returns current user if session is valid
    """
    from models.core import User
    from datetime import datetime, timezone
    
    # Try cookie first
    session_token = request.cookies.get("dhruv_ai_session")
    
    # Fallback to Authorization header
    if not session_token:
        auth_header = request.headers.get("Authorization")
        if auth_header and auth_header.startswith("Bearer "):
            session_token = auth_header.split(" ")[1]
    
    # Also check old JWT cookie for backward compatibility
    if not session_token:
        session_token = request.cookies.get("dhruv_ai_auth")
    
    if not session_token:
        raise HTTPException(status_code=401, detail="No active session")
    
    # Find user with valid session
    current_time_iso = datetime.now(timezone.utc).isoformat()
    user_doc = await db.users.find_one({
        "session_token": session_token,
        "session_expiry": {"$gt": current_time_iso}
    })
    
    if not user_doc:
        raise HTTPException(status_code=401, detail="Session expired or invalid")
    
    user = User(**user_doc)
    
    return {
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "photo_url": user.photo_url,
            "exam_type": user.exam_type,
            "profile_completed": user.profile_completed,
            "subscription_type": user.subscription_type
        }
    }



@router.get("/csrf-token")
async def get_csrf_token(request: Request):
    """
    Get CSRF token for state-changing requests
    The token is automatically generated and sent in the X-CSRF-Token header
    """
    import secrets
    
    # Generate new CSRF token
    csrf_token = secrets.token_urlsafe(32)
    
    # Store in session
    if hasattr(request, "session"):
        request.session["csrf_token"] = csrf_token
    
    return {
        "csrf_token": csrf_token,
        "message": "CSRF token generated. Include this token in X-CSRF-Token header for all POST/PUT/PATCH/DELETE requests."
    }


@router.post("/profile/complete")
async def complete_profile(
    profile_data: ProfileCompleteRequest,
    request: Request,
    db = Depends(get_database)
):
    """
    Complete user profile after first Gmail login
    Sets profile_completed to True
    """
    from models.core import User
    from datetime import datetime, timezone
    
    # Get current user from session
    session_token = request.cookies.get("dhruv_ai_session")
    if not session_token:
        auth_header = request.headers.get("Authorization")
        if auth_header and auth_header.startswith("Bearer "):
            session_token = auth_header.split(" ")[1]
    
    if not session_token:
        raise HTTPException(status_code=401, detail="Authentication required")
    
    # Compare with ISO string format (consistent with storage)
    current_time_iso = datetime.now(timezone.utc).isoformat()
    user_doc = await db.users.find_one({
        "session_token": session_token,
        "session_expiry": {"$gt": current_time_iso}
    })
    
    if not user_doc:
        raise HTTPException(status_code=401, detail="Session expired")
    
    # Update user profile
    update_data = {
        "exam_type": profile_data.exam_type,
        "profile_completed": True
    }
    
    if profile_data.study_goal:
        update_data["study_goal"] = profile_data.study_goal
    if profile_data.preferred_mode:
        update_data["preferred_mode"] = profile_data.preferred_mode
    if profile_data.timezone:
        update_data["timezone"] = profile_data.timezone
    if profile_data.country:
        update_data["country"] = profile_data.country
    if profile_data.target_year:
        update_data["target_year"] = profile_data.target_year
    
    await db.users.update_one(
        {"user_id": user_doc["user_id"]},
        {"$set": update_data}
    )
    
    # Fetch updated user
    updated_user_doc = await db.users.find_one({"user_id": user_doc["user_id"]})
    user = User(**updated_user_doc)
    
    return {
        "message": "Profile completed successfully",
        "user": {
            "user_id": user.user_id,
            "full_name": user.full_name,
            "email": user.email,
            "photo_url": user.photo_url,
            "exam_type": user.exam_type,
            "profile_completed": user.profile_completed,
            "subscription_type": user.subscription_type
        }
    }


# =============================================================================
# JWT REFRESH TOKEN ENDPOINTS
# =============================================================================

@router.post("/token/refresh")
async def refresh_access_token(
    request: Request,
    db = Depends(get_database)
):
    """
    Refresh access token using refresh token
    Implements token rotation for security
    
    Expects refresh_token in request body:
    {
        "refresh_token": "..."
    }
    
    Returns new access and refresh tokens
    """
    from services.jwt_service import JWTService
    from datetime import datetime, timezone
    import json
    
    # Get refresh token from request body
    try:
        body = await request.json()
        refresh_token = body.get("refresh_token")
    except:
        raise HTTPException(status_code=400, detail="Invalid request body")
    
    if not refresh_token:
        raise HTTPException(status_code=400, detail="Refresh token required")
    
    # Initialize JWT service
    jwt_service = JWTService(db)
    
    # Verify and rotate refresh token
    payload = await jwt_service.verify_refresh_token(refresh_token)
    if not payload:
        raise HTTPException(status_code=401, detail="Invalid or expired refresh token")
    
    user_id = payload.get("sub")
    
    # Create new token pair with rotation
    result = await jwt_service.rotate_refresh_token(refresh_token, user_id)
    if not result:
        raise HTTPException(status_code=401, detail="Token rotation failed")
    
    new_access_token, new_refresh_token = result
    
    return {
        "access_token": new_access_token,
        "refresh_token": new_refresh_token,
        "token_type": "bearer",
        "expires_in": jwt_service.ACCESS_TOKEN_EXPIRE_MINUTES * 60
    }


@router.post("/token/revoke")
async def revoke_refresh_token(
    request: Request,
    db = Depends(get_database)
):
    """
    Revoke a refresh token (logout from specific device)
    
    Expects refresh_token in request body:
    {
        "refresh_token": "..."
    }
    """
    from services.jwt_service import JWTService
    
    # Get refresh token from request body
    try:
        body = await request.json()
        refresh_token = body.get("refresh_token")
    except:
        raise HTTPException(status_code=400, detail="Invalid request body")
    
    if not refresh_token:
        raise HTTPException(status_code=400, detail="Refresh token required")
    
    # Initialize JWT service
    jwt_service = JWTService(db)
    
    # Revoke token
    success = await jwt_service.revoke_refresh_token(refresh_token)
    
    if not success:
        # Don't reveal whether token exists
        return {"message": "Token revoked successfully"}
    
    return {"message": "Token revoked successfully"}


@router.post("/token/revoke-all")
async def revoke_all_tokens(
    request: Request,
    db = Depends(get_database)
):
    """
    Revoke all refresh tokens for current user (logout from all devices)
    Requires valid authentication
    """
    from services.jwt_service import JWTService
    from datetime import datetime, timezone
    
    # Get current user from session
    session_token = request.cookies.get("dhruv_ai_session")
    if not session_token:
        raise HTTPException(status_code=401, detail="Authentication required")
    
    # Find user by session
    current_time_iso = datetime.now(timezone.utc).isoformat()
    user_doc = await db.users.find_one({
        "session_token": session_token,
        "session_expiry": {"$gt": current_time_iso}
    })
    
    if not user_doc:
        raise HTTPException(status_code=401, detail="Session expired")
    
    # Revoke all tokens
    jwt_service = JWTService(db)
    count = await jwt_service.revoke_all_user_tokens(user_doc["user_id"])
    
    return {
        "message": f"Revoked {count} refresh token(s)",
        "count": count

    }