import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Image as ImageIcon, X } from 'lucide-react';
import DynamicSceneComposer from './DynamicSceneComposer'; // Importing the DynamicSceneComposer

/**
 * VisualConceptBlock - Renders dynamic visuals generated by the neuro-symbolic visual engine
 * Supports both inline SVG and base64 images with expand/collapse
 */
const VisualConceptBlock = ({ visualData }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  if (!visualData || !visualData.generated) {
    return null;
  }

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.3 }}
      className="my-4"
    >
      {/* Compact View */}
      {!isExpanded && (
        <button
          onClick={() => setIsExpanded(true)}
          className="flex items-center space-x-2 px-4 py-2 bg-purple-50 hover:bg-purple-100 text-purple-700 rounded-lg transition-colors w-full"
        >
          <ImageIcon className="w-4 h-4" />
          <span className="text-sm font-medium">View Concept Visual</span>
        </button>
      )}

      {/* Expanded View */}
      {isExpanded && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          exit={{ opacity: 0, height: 0 }}
          className="p-4 bg-gray-50 rounded-lg border border-gray-200"
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center space-x-2">
              <ImageIcon className="w-4 h-4 text-purple-600" />
              <span className="text-sm font-medium text-gray-700">Concept Visualization</span>
            </div>
            <button
              onClick={() => setIsExpanded(false)}
              className="text-gray-400 hover:text-gray-600 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          <div className="bg-white p-4 rounded-lg">
            <DynamicSceneComposer visualData={visualData} /> {/* Using DynamicSceneComposer for dynamic scene */}
          </div>
        </motion.div>
      )}
    </motion.div>
  );
};

export default VisualConceptBlock;
