import React from 'react';
import { motion } from 'framer-motion';
import { Image as ImageIcon, X } from 'lucide-react';
import DynamicSceneComposer from './DynamicSceneComposer'; // Importing the DynamicSceneComposer

/**
 * VisualConceptBlock - Renders dynamic visuals generated by the neuro-symbolic visual engine
 * Supports both inline SVG and base64 images with expand/collapse
 */
const VisualConceptBlock = ({ visualData }) => {
  if (!visualData || !visualData.generated) {
    return null;
  }

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.3 }}
      className="my-4"
    >
      <motion.div
        initial={{ opacity: 0, height: 0 }}
        animate={{ opacity: 1, height: 'auto' }}
        exit={{ opacity: 0, height: 0 }}
        className="p-2"
      >
        <DynamicSceneComposer visualData={visualData} />
      </motion.div>
    </motion.div>
  );
};

export default VisualConceptBlock;
